using System;
using System.Collections.Generic;
using System.Linq;

namespace EmuSen.Mistress.BigPicture.Theme
{
    public enum ThemeViewScope { Any, System, Gamelist }

    public enum ThemeElementGroup { Primary, Secondary, Special }

    [Flags]
    public enum ThemeElementViews { System = 1, Gamelist = 2, All = 4, SystemAndGamelist = System | Gamelist }

    // How a STRING property's text is read: free text, one of a set, a list of a set, or a PATH keyed by an attribute.
    public enum ThemeValueShape { Single, Enum, List, Keyed }

    // Per-axis rules the reference section gives for particular pairs - see EmuSen_BigPicture.md §12.2.
    public enum PairRule { Clamp, ZeroAxisAuto, MinusOneMatchesOther, OneAxisOnly }

    // Defaults the reference states in words rather than as a literal - see EmuSen_BigPicture.md §12.2.
    public enum ComputedDefault
    {
        None,
        SystemFullName,
        ElementWidth,
        OneAndAHalfFontSize,
        HelpPosByOrientation,
        HelpFontSizeByOrientation,
        InterpolationByRotation,
        ContainerForDescription,
        DisplayRelativeForLastPlayed,
        ContainerStartDelayByType,
    }

    // One documented property: its type, default, range, values and the view it is limited to.
    public sealed record ThemePropertySpec(string Name, ThemePropertyType Type)
    {
        public string? Default { get; init; }
        public string? DefaultSameAs { get; init; }
        public ComputedDefault Computed { get; init; }
        public float? Min { get; init; }
        public float? Max { get; init; }
        public float? MaxY { get; init; }
        public PairRule Rule { get; init; }
        public ThemeValueShape Shape { get; init; }
        public IReadOnlyList<string> Values { get; init; } = [];
        public int MaxItems { get; init; }
        public string? KeyAttribute { get; init; }
        public ThemeViewScope OnlyIn { get; init; }
        public string? Deferred { get; init; }
    }

    // One documented element type and its properties.
    public sealed class ThemeElementSpec
    {
        private readonly Dictionary<string, ThemePropertySpec> _byName;

        public ThemeElementSpec(string type, ThemeElementGroup group, ThemeElementViews views, IReadOnlyList<ThemePropertySpec> properties)
        {
            Type = type;
            Group = group;
            Views = views;
            Properties = properties;
            _byName = properties.ToDictionary(p => p.Name, StringComparer.Ordinal);
        }

        public string Type { get; }
        public ThemeElementGroup Group { get; }
        public ThemeElementViews Views { get; }
        public IReadOnlyList<ThemePropertySpec> Properties { get; }

        // Only helpsystem, clock and systemstatus lack one; they draw above everything - see EmuSen_BigPicture.md §12.2.
        public float? DefaultZIndex => _byName.TryGetValue("zIndex", out ThemePropertySpec? z) ? float.Parse(z.Default!, System.Globalization.CultureInfo.InvariantCulture) : null;

        public ThemePropertySpec? Find(string name) => _byName.GetValueOrDefault(name);
    }

    // Every element type and property in THEMES.md's reference section, plus the sound element - see EmuSen_BigPicture.md §12.2.
    public static class ThemeCatalog
    {
        public const string VideoDeferred = "video playback is deferred (EmuSen_BigPicture.md §10.1, Q4)";

        public static IReadOnlyList<ThemeElementSpec> Elements { get; } =
        [
            new ThemeElementSpec("carousel", ThemeElementGroup.Primary, ThemeElementViews.SystemAndGamelist,
            [
                Pair("pos", "0 0.38378"),
                Pair("size", "1 0.2324", 0.05f, 2f),
                Pair("origin", "0 0", 0f, 1f),
                Enum("type", "horizontal", "horizontal vertical horizontalWheel verticalWheel"),
                Path("staticImage") with { OnlyIn = ThemeViewScope.System },
                List("imageType", "marquee", "marquee cover backcover 3dbox physicalmedia screenshot titlescreen miximage fanart none", 2) with { OnlyIn = ThemeViewScope.Gamelist },
                Path("defaultImage"),
                Path("defaultFolderImage") with { DefaultSameAs = "defaultImage", OnlyIn = ThemeViewScope.Gamelist },
                Float("maxItemCount", "3", 0.5f, 30f),
                UInt("itemsBeforeCenter", "8", 0f, 20f),
                UInt("itemsAfterCenter", "8", 0f, 20f),
                Enum("itemStacking", "centered", "centered ascending ascendingRaised descending descendingRaised"),
                Pair("selectedItemMargins", "0 0", -1f, 1f),
                Pair("selectedItemOffset", "0 0", -1f, 1f),
                Pair("itemSize", "0.25 0.155", 0.05f, 1f),
                Float("itemScale", "1.2", 0.2f, 3f),
                Float("itemRotation", "7.5"),
                Pair("itemRotationOrigin", "-3 0.5"),
                Bool("itemAxisHorizontal", "false"),
                Float("itemAxisRotation", "0"),
                Enum("imageFit", "contain", "contain fill cover"),
                Pair("imageCropPos", "0.5 0.5", 0f, 1f),
                Enum("imageInterpolation", "linear", "nearest linear"),
                Float("imageCornerRadius", "0", 0f, 0.5f),
                Color("imageColor", "FFFFFFFF"),
                Color("imageColorEnd", null) with { DefaultSameAs = "imageColor" },
                Enum("imageGradientType", "horizontal", "horizontal vertical"),
                Color("imageSelectedColor", null) with { DefaultSameAs = "imageColor" },
                Color("imageSelectedColorEnd", null) with { DefaultSameAs = "imageSelectedColor" },
                Enum("imageSelectedGradientType", "horizontal", "horizontal vertical"),
                Float("imageBrightness", "0", -2f, 2f),
                Float("imageSaturation", "1", 0f, 1f),
                Enum("itemTransitions", "animate", "animate instant"),
                Float("itemDiagonalOffset", "0", -0.5f, 0.5f),
                Enum("itemHorizontalAlignment", "center", "left center right"),
                Enum("itemVerticalAlignment", "center", "top center bottom"),
                Enum("wheelHorizontalAlignment", "center", "left center right"),
                Enum("wheelVerticalAlignment", "center", "top center bottom"),
                Float("horizontalOffset", "0", -1f, 1f),
                Float("verticalOffset", "0", -1f, 1f),
                Bool("reflections", "false"),
                Float("reflectionsOpacity", "0.5", 0.1f, 1f),
                Float("reflectionsFalloff", "1", 0f, 10f),
                Float("unfocusedItemOpacity", "0.5", 0.1f, 1f),
                Float("unfocusedItemSaturation", "1", 0f, 1f),
                Float("unfocusedItemDimming", "1", 0f, 1f),
                Bool("fastScrolling", "false"),
                Color("color", "FFFFFFD8"),
                Color("colorEnd", null) with { DefaultSameAs = "color" },
                Enum("gradientType", "horizontal", "horizontal vertical"),
                Str("text", null) with { OnlyIn = ThemeViewScope.System, Computed = ComputedDefault.SystemFullName },
                Float("textRelativeScale", "1", 0.2f, 1f),
                Float("textBackgroundCornerRadius", "0", 0f, 0.5f),
                Color("textColor", "000000FF"),
                Color("textBackgroundColor", "FFFFFF00"),
                Color("textSelectedColor", null) with { DefaultSameAs = "textColor" },
                Color("textSelectedBackgroundColor", null) with { DefaultSameAs = "textBackgroundColor" },
                Bool("textHorizontalScrolling", "false"),
                Float("textHorizontalScrollSpeed", "1", 0.1f, 10f),
                Float("textHorizontalScrollDelay", "3", 0f, 10f),
                Float("textHorizontalScrollGap", "1.5", 0.1f, 5f),
                Path("fontPath"),
                Float("fontSize", "0.085", 0.001f, 1.5f),
                Enum("letterCase", "none", "none uppercase lowercase capitalize"),
                Enum("letterCaseAutoCollections", null, "none uppercase lowercase capitalize") with { DefaultSameAs = "letterCase", OnlyIn = ThemeViewScope.System },
                Enum("letterCaseCustomCollections", null, "none uppercase lowercase capitalize") with { DefaultSameAs = "letterCase" },
                Float("lineSpacing", "1.5", 0.5f, 3f),
                Bool("systemNameSuffix", "true") with { OnlyIn = ThemeViewScope.Gamelist },
                Enum("letterCaseSystemNameSuffix", "uppercase", "uppercase lowercase capitalize") with { OnlyIn = ThemeViewScope.Gamelist },
                Bool("fadeAbovePrimary", "false") with { OnlyIn = ThemeViewScope.System },
                Float("zIndex", "50"),
            ]),
            new ThemeElementSpec("grid", ThemeElementGroup.Primary, ThemeElementViews.SystemAndGamelist,
            [
                Pair("pos", "0 0.1"),
                Pair("size", "1 0.8", 0.05f, 1f),
                Pair("origin", "0 0", 0f, 1f),
                Path("staticImage") with { OnlyIn = ThemeViewScope.System },
                List("imageType", "marquee", "marquee cover backcover 3dbox physicalmedia screenshot titlescreen miximage fanart none", 2) with { OnlyIn = ThemeViewScope.Gamelist },
                Path("defaultImage"),
                Path("defaultFolderImage") with { DefaultSameAs = "defaultImage", OnlyIn = ThemeViewScope.Gamelist },
                Pair("itemSize", "0.15 0.25", 0.05f, 1f) with { Rule = PairRule.MinusOneMatchesOther },
                Float("itemScale", "1.05", 0.5f, 2f),
                Pair("itemSpacing", null, 0f, 0.1f) with { Rule = PairRule.MinusOneMatchesOther },
                Bool("scaleInwards", "false"),
                Bool("fractionalRows", "false"),
                Enum("itemTransitions", "animate", "animate instant"),
                Enum("rowTransitions", "animate", "animate instant"),
                Float("unfocusedItemOpacity", "1", 0.1f, 1f),
                Float("unfocusedItemSaturation", "1", 0f, 1f),
                Float("unfocusedItemDimming", "1", 0f, 1f),
                Enum("imageFit", "contain", "contain fill cover"),
                Pair("imageCropPos", "0.5 0.5", 0f, 1f),
                Enum("imageInterpolation", "linear", "nearest linear"),
                Float("imageRelativeScale", "1", 0.2f, 1f),
                Float("imageCornerRadius", "0", 0f, 0.5f),
                Color("imageColor", "FFFFFFFF"),
                Color("imageColorEnd", null) with { DefaultSameAs = "imageColor" },
                Enum("imageGradientType", "horizontal", "horizontal vertical"),
                Color("imageSelectedColor", null) with { DefaultSameAs = "imageColor" },
                Color("imageSelectedColorEnd", null) with { DefaultSameAs = "imageSelectedColor" },
                Enum("imageSelectedGradientType", "horizontal", "horizontal vertical"),
                Float("imageBrightness", "0", -2f, 2f),
                Float("imageSaturation", "1", 0f, 1f),
                Path("backgroundImage"),
                Float("backgroundRelativeScale", "1", 0.2f, 1f),
                Float("backgroundCornerRadius", "0", 0f, 0.5f),
                Color("backgroundColor", null),
                Color("backgroundColorEnd", null) with { DefaultSameAs = "backgroundColor" },
                Enum("backgroundGradientType", "horizontal", "horizontal vertical"),
                Path("selectorImage"),
                Float("selectorRelativeScale", "1", 0.2f, 1f),
                Enum("selectorLayer", "top", "bottom middle top"),
                Float("selectorCornerRadius", "0", 0f, 0.5f),
                Color("selectorColor", null),
                Color("selectorColorEnd", null) with { DefaultSameAs = "selectorColor" },
                Enum("selectorGradientType", "horizontal", "horizontal vertical"),
                Str("text", null) with { OnlyIn = ThemeViewScope.System, Computed = ComputedDefault.SystemFullName },
                Float("textRelativeScale", "1", 0.2f, 1f),
                Float("textBackgroundCornerRadius", "0", 0f, 0.5f),
                Color("textColor", "000000FF"),
                Color("textBackgroundColor", "FFFFFF00"),
                Color("textSelectedColor", null) with { DefaultSameAs = "textColor" },
                Color("textSelectedBackgroundColor", null) with { DefaultSameAs = "textBackgroundColor" },
                Bool("textHorizontalScrolling", "false"),
                Float("textHorizontalScrollSpeed", "1", 0.1f, 10f),
                Float("textHorizontalScrollDelay", "3", 0f, 10f),
                Float("textHorizontalScrollGap", "1.5", 0.1f, 5f),
                Path("fontPath"),
                Float("fontSize", "0.045", 0.001f, 1.5f),
                Enum("letterCase", "none", "none uppercase lowercase capitalize"),
                Enum("letterCaseAutoCollections", null, "none uppercase lowercase capitalize") with { DefaultSameAs = "letterCase", OnlyIn = ThemeViewScope.System },
                Enum("letterCaseCustomCollections", null, "none uppercase lowercase capitalize") with { DefaultSameAs = "letterCase" },
                Float("lineSpacing", "1.5", 0.5f, 3f),
                Bool("systemNameSuffix", "true") with { OnlyIn = ThemeViewScope.Gamelist },
                Enum("letterCaseSystemNameSuffix", "uppercase", "uppercase lowercase capitalize") with { OnlyIn = ThemeViewScope.Gamelist },
                Bool("fadeAbovePrimary", "false") with { OnlyIn = ThemeViewScope.System },
                Float("zIndex", "50"),
            ]),
            new ThemeElementSpec("textlist", ThemeElementGroup.Primary, ThemeElementViews.SystemAndGamelist,
            [
                Pair("pos", "0 0.1"),
                Pair("size", "1 0.8", 0.05f, 1f),
                Pair("origin", "0 0", 0f, 1f),
                Float("selectorWidth", null, 0f, 1f) with { Computed = ComputedDefault.ElementWidth },
                Float("selectorHeight", null, 0f, 1f) with { Computed = ComputedDefault.OneAndAHalfFontSize },
                Float("selectorHorizontalOffset", "0", -1f, 1f),
                Float("selectorVerticalOffset", "0", -1f, 1f),
                Color("selectorColor", "333333FF"),
                Color("selectorColorEnd", "333333FF"),
                Enum("selectorGradientType", "horizontal", "horizontal vertical"),
                Path("selectorImagePath"),
                Bool("selectorImageTile", "false"),
                Color("primaryColor", "0000FFFF"),
                Color("secondaryColor", "00FF00FF"),
                Color("selectedColor", null) with { DefaultSameAs = "primaryColor" },
                Color("selectedSecondaryColor", null) with { DefaultSameAs = "selectedColor" },
                Color("selectedBackgroundColor", "00000000"),
                Color("selectedSecondaryBackgroundColor", null) with { DefaultSameAs = "selectedBackgroundColor" },
                Pair("selectedBackgroundMargins", "0 0", 0f, 0.5f),
                Float("selectedBackgroundCornerRadius", "0", 0f, 0.5f),
                Bool("textHorizontalScrolling", "true"),
                Float("textHorizontalScrollSpeed", "1", 0.1f, 10f),
                Float("textHorizontalScrollDelay", "3", 0f, 10f),
                Float("textHorizontalScrollGap", "1.5", 0.1f, 5f),
                Path("fontPath"),
                Float("fontSize", "0.045"),
                Enum("horizontalAlignment", "left", "left center right"),
                Float("horizontalMargin", "0"),
                Enum("letterCase", "none", "none uppercase lowercase capitalize"),
                Enum("letterCaseAutoCollections", null, "none uppercase lowercase capitalize") with { DefaultSameAs = "letterCase", OnlyIn = ThemeViewScope.System },
                Enum("letterCaseCustomCollections", null, "none uppercase lowercase capitalize") with { DefaultSameAs = "letterCase" },
                Float("lineSpacing", "1.5", 0.5f, 3f),
                Enum("indicators", "symbols", "none ascii symbols"),
                Enum("collectionIndicators", "symbols", "ascii symbols"),
                Bool("systemNameSuffix", "true") with { OnlyIn = ThemeViewScope.Gamelist },
                Enum("letterCaseSystemNameSuffix", "uppercase", "uppercase lowercase capitalize") with { OnlyIn = ThemeViewScope.Gamelist },
                Bool("fadeAbovePrimary", "false") with { OnlyIn = ThemeViewScope.System },
                Float("zIndex", "50"),
            ]),
            new ThemeElementSpec("image", ThemeElementGroup.Secondary, ThemeElementViews.SystemAndGamelist,
            [
                Pair("pos", null),
                Pair("size", null, 0.001f, 3f) with { Rule = PairRule.ZeroAxisAuto },
                Pair("maxSize", null, 0.001f, 3f),
                Pair("cropSize", null, 0.001f, 3f),
                Pair("cropPos", "0.5 0.5", 0f, 1f),
                Pair("origin", "0 0", 0f, 1f),
                Float("rotation", "0"),
                Pair("rotationOrigin", "0.5 0.5", 0f, 1f),
                Enum("stationary", "never", "withinView betweenViews always never"),
                Bool("renderDuringTransitions", "true"),
                Bool("flipHorizontal", "false"),
                Bool("flipVertical", "false"),
                Path("path"),
                Path("gameOverridePath") with { OnlyIn = ThemeViewScope.Gamelist },
                Path("default"),
                List("imageType", null, "image miximage marquee screenshot titlescreen cover backcover 3dbox physicalmedia fanart", 0),
                Bool("metadataElement", "false"),
                Str("gameselector", null),
                UInt("gameselectorEntry", "0", 0f, null) with { OnlyIn = ThemeViewScope.System },
                Bool("tile", "false"),
                Pair("tileSize", null, 0f, 1f) with { Rule = PairRule.ZeroAxisAuto },
                Enum("tileHorizontalAlignment", "left", "left right"),
                Enum("tileVerticalAlignment", "bottom", "top bottom"),
                Enum("interpolation", null, "nearest linear") with { Computed = ComputedDefault.InterpolationByRotation },
                Bool("mipmap", "false"),
                Float("cornerRadius", "0", 0f, 0.5f),
                Color("color", "FFFFFFFF"),
                Color("colorEnd", null) with { DefaultSameAs = "color" },
                Enum("gradientType", "horizontal", "horizontal vertical"),
                Bool("scrollFadeIn", "false"),
                Float("brightness", "0", -2f, 2f),
                Float("opacity", "1", 0f, 1f),
                Float("saturation", "1", 0f, 1f),
                Bool("visible", "true"),
                Float("zIndex", "30"),
            ]),
            new ThemeElementSpec("video", ThemeElementGroup.Secondary, ThemeElementViews.SystemAndGamelist,
            [
                Pair("pos", null),
                Pair("size", null, 0.01f, 2f) with { Rule = PairRule.ZeroAxisAuto },
                Pair("maxSize", null, 0.01f, 2f),
                Pair("cropSize", null, 0.01f, 2f),
                Pair("cropPos", "0.5 0.5", 0f, 1f),
                Pair("imageSize", null, 0.01f, 2f) with { DefaultSameAs = "size", Rule = PairRule.ZeroAxisAuto },
                Pair("imageMaxSize", null, 0.01f, 2f) with { DefaultSameAs = "maxSize" },
                Pair("imageCropSize", null, 0.01f, 2f) with { DefaultSameAs = "cropSize" },
                Pair("imageCropPos", "0.5 0.5", 0f, 1f),
                Pair("origin", "0 0", 0f, 1f),
                Float("rotation", "0"),
                Pair("rotationOrigin", "0.5 0.5", 0f, 1f),
                Enum("stationary", "never", "withinView betweenViews always never"),
                Path("path") with { Deferred = VideoDeferred },
                Path("default") with { Deferred = VideoDeferred },
                Path("defaultImage"),
                List("imageType", null, "image miximage marquee screenshot titlescreen cover backcover 3dbox physicalmedia fanart none", 0),
                Bool("metadataElement", "false"),
                Str("gameselector", null),
                UInt("gameselectorEntry", "0", 0f, null) with { OnlyIn = ThemeViewScope.System },
                UInt("iterationCount", "0", 0f, 10f) with { Deferred = VideoDeferred },
                Enum("onIterationsDone", "nothing", "nothing image") with { Deferred = VideoDeferred },
                Bool("audio", "true") with { Deferred = VideoDeferred },
                Enum("interpolation", null, "nearest linear") with { Computed = ComputedDefault.InterpolationByRotation },
                Float("imageCornerRadius", "0", 0f, 0.5f),
                Float("videoCornerRadius", "0", 0f, 0.5f) with { Deferred = VideoDeferred },
                Color("color", "FFFFFFFF"),
                Color("colorEnd", null) with { DefaultSameAs = "color" },
                Enum("gradientType", "horizontal", "horizontal vertical"),
                Bool("pillarboxes", "true") with { Deferred = VideoDeferred },
                Pair("pillarboxThreshold", "0.85 0.90", 0.2f, 1f) with { Deferred = VideoDeferred },
                Bool("scanlines", "false") with { Deferred = VideoDeferred },
                Float("delay", "1.5", 0f, 15f) with { Deferred = VideoDeferred },
                Enum("fadeInType", "black", "black transparent") with { Deferred = VideoDeferred },
                Float("fadeInTime", "1", 0f, 8f) with { Deferred = VideoDeferred },
                Bool("scrollFadeIn", "false"),
                Float("brightness", "0", -2f, 2f),
                Float("opacity", "1", 0f, 1f),
                Float("saturation", "1", 0f, 1f),
                Bool("visible", "true"),
                Float("zIndex", "30"),
            ]),
            new ThemeElementSpec("animation", ThemeElementGroup.Secondary, ThemeElementViews.SystemAndGamelist,
            [
                Pair("pos", null),
                Pair("size", null, 0.01f, 1f) with { Rule = PairRule.ZeroAxisAuto },
                Pair("maxSize", null, 0.01f, 1f),
                Pair("origin", "0 0", 0f, 1f),
                Float("rotation", "0"),
                Pair("rotationOrigin", "0.5 0.5", 0f, 1f),
                Enum("stationary", "never", "withinView betweenViews always never"),
                Bool("metadataElement", "false"),
                Path("path"),
                Float("speed", "1", 0.2f, 3f),
                Enum("direction", "normal", "normal reverse alternate alternateReverse"),
                UInt("iterationCount", "0", 0f, 10f),
                Enum("interpolation", null, "nearest linear") with { Computed = ComputedDefault.InterpolationByRotation },
                Float("cornerRadius", "0", 0f, 0.5f),
                Color("color", "FFFFFFFF"),
                Color("colorEnd", null) with { DefaultSameAs = "color" },
                Enum("gradientType", "horizontal", "horizontal vertical"),
                Float("brightness", "0", -2f, 2f),
                Float("opacity", "1", 0f, 1f),
                Float("saturation", "1", 0f, 1f),
                Bool("visible", "true"),
                Float("zIndex", "35"),
            ]),
            new ThemeElementSpec("badges", ThemeElementGroup.Secondary, ThemeElementViews.Gamelist,
            [
                Pair("pos", null),
                Pair("size", "0.15 0.20", 0.03f, 1f),
                Pair("origin", "0 0", 0f, 1f),
                Float("rotation", "0"),
                Pair("rotationOrigin", "0.5 0.5", 0f, 1f),
                Enum("stationary", "never", "withinView betweenViews always never"),
                Enum("horizontalAlignment", null, "left center right"),
                Enum("direction", "row", "row column"),
                UInt("lines", "3"),
                UInt("itemsPerLine", "4"),
                Pair("itemMargin", "0.01 0.01", 0f, 0.2f) with { Rule = PairRule.MinusOneMatchesOther },
                List("slots", null, "collection folder favorite completed kidgame broken controller altemulator manual all", 0),
                Pair("controllerPos", "0.5 0.5", -1f, 2f),
                Float("controllerSize", "0.5", 0.1f, 2f),
                Keyed("customBadgeIcon", "badge", "collection folder favorite completed kidgame broken controller altemulator manual"),
                Keyed("customControllerIcon", "controller", "gamepad_generic gamepad_nintendo_nes gamepad_nintendo_snes gamepad_nintendo_64 gamepad_nintendo_gamecube gamepad_playstation gamepad_sega_master_system gamepad_sega_md_3_buttons gamepad_sega_md_6_buttons gamepad_sega_dreamcast gamepad_xbox joystick_generic joystick_arcade_no_buttons joystick_arcade_no_buttons_twin joystick_arcade_1_button joystick_arcade_2_buttons joystick_arcade_3_buttons joystick_arcade_4_buttons joystick_arcade_5_buttons joystick_arcade_6_buttons keyboard_generic keyboard_and_mouse_generic mouse_generic mouse_amiga lightgun_generic lightgun_nintendo steering_wheel_generic flight_stick_generic spinner_generic trackball_generic wii_remote_nintendo wii_remote_and_nunchuk_nintendo joycon_left_or_right_nintendo joycon_pair_nintendo xbox_kinect unknown"),
                Pair("folderLinkPos", "0.5 0.5", -1f, 2f),
                Float("folderLinkSize", "0.5", 0.1f, 1f),
                Path("customFolderLinkIcon"),
                Color("badgeIconColor", "FFFFFFFF"),
                Color("badgeIconColorEnd", null) with { DefaultSameAs = "badgeIconColor" },
                Enum("badgeIconGradientType", "horizontal", "horizontal vertical"),
                Color("controllerIconColor", "FFFFFFFF"),
                Color("controllerIconColorEnd", null) with { DefaultSameAs = "controllerIconColor" },
                Enum("controllerIconGradientType", "horizontal", "horizontal vertical"),
                Color("folderLinkIconColor", "FFFFFFFF"),
                Color("folderLinkIconColorEnd", null) with { DefaultSameAs = "folderLinkIconColor" },
                Enum("folderLinkIconGradientType", "horizontal", "horizontal vertical"),
                Enum("interpolation", null, "nearest linear") with { Computed = ComputedDefault.InterpolationByRotation },
                Float("opacity", "1", 0f, 1f),
                Bool("visible", "true"),
                Float("zIndex", "35"),
            ]),
            new ThemeElementSpec("text", ThemeElementGroup.Secondary, ThemeElementViews.SystemAndGamelist,
            [
                Pair("pos", null),
                Pair("size", null),
                Pair("origin", "0 0", 0f, 1f),
                Float("rotation", "0"),
                Pair("rotationOrigin", "0.5 0.5", 0f, 1f),
                Enum("stationary", "never", "withinView betweenViews always never"),
                Str("text", null),
                Enum("systemdata", null, "name fullname gamecount gamecountGames gamecountGamesNoText gamecountFavorites gamecountFavoritesNoText") with { OnlyIn = ThemeViewScope.System },
                Enum("metadata", null, "name description rating developer publisher genre players favorite completed kidgame broken manual playcount playtime controller altemulator emulator physicalName physicalNameExtension systemName systemFullname sourceSystemName sourceSystemFullname"),
                Str("defaultValue", null),
                Bool("systemNameSuffix", "true"),
                Enum("letterCaseSystemNameSuffix", "uppercase", "uppercase lowercase capitalize"),
                Bool("metadataElement", "false"),
                Str("gameselector", null) with { OnlyIn = ThemeViewScope.System },
                UInt("gameselectorEntry", "0", 0f, null) with { OnlyIn = ThemeViewScope.System },
                Bool("container", null) with { Computed = ComputedDefault.ContainerForDescription },
                Enum("containerType", "vertical", "vertical horizontal"),
                Bool("containerVerticalSnap", "true"),
                Float("containerScrollSpeed", "1", 0.1f, 10f),
                Float("containerStartDelay", null, 0f, 10f) with { Computed = ComputedDefault.ContainerStartDelayByType },
                Float("containerResetDelay", "7", 0f, 20f),
                Float("containerScrollGap", "1.5", 0.1f, 5f),
                Path("fontPath"),
                Float("fontSize", "0.045", 0.001f, 1.5f),
                Enum("horizontalAlignment", "left", "left center right"),
                Enum("verticalAlignment", "center", "top center bottom"),
                Color("color", "000000FF"),
                Color("backgroundColor", "00000000"),
                Pair("backgroundMargins", "0 0", 0f, 0.5f),
                Float("backgroundCornerRadius", "0", 0f, 0.5f),
                Enum("letterCase", "none", "none uppercase lowercase capitalize"),
                Float("lineSpacing", "1.5", 0.5f, 3f),
                Float("opacity", "1", 0f, 1f),
                Bool("visible", "true"),
                Float("zIndex", "40"),
            ]),
            new ThemeElementSpec("datetime", ThemeElementGroup.Secondary, ThemeElementViews.SystemAndGamelist,
            [
                Pair("pos", null),
                Pair("size", null),
                Pair("origin", "0 0", 0f, 1f),
                Float("rotation", "0"),
                Pair("rotationOrigin", "0.5 0.5", 0f, 1f),
                Enum("stationary", "never", "withinView betweenViews always never"),
                Enum("metadata", null, "releasedate lastplayed"),
                Str("defaultValue", null),
                Str("gameselector", null),
                UInt("gameselectorEntry", "0", 0f, null) with { OnlyIn = ThemeViewScope.System },
                Path("fontPath"),
                Float("fontSize", "0.045", 0.001f, 1.5f),
                Enum("horizontalAlignment", "left", "left center right"),
                Enum("verticalAlignment", "center", "top center bottom"),
                Color("color", null),
                Color("backgroundColor", null),
                Pair("backgroundMargins", "0 0", 0f, 0.5f),
                Float("backgroundCornerRadius", "0", 0f, 0.5f),
                Enum("letterCase", "none", "none uppercase lowercase capitalize"),
                Float("lineSpacing", "1.5", 0.5f, 3f),
                Str("format", "%Y-%m-%d"),
                Bool("displayRelative", null) with { Computed = ComputedDefault.DisplayRelativeForLastPlayed },
                Float("opacity", "1", 0f, 1f),
                Bool("visible", "true"),
                Float("zIndex", "40"),
            ]),
            new ThemeElementSpec("gamelistinfo", ThemeElementGroup.Secondary, ThemeElementViews.Gamelist,
            [
                Pair("pos", null),
                Pair("size", null),
                Pair("origin", "0 0", 0f, 1f),
                Float("rotation", "0"),
                Pair("rotationOrigin", "0.5 0.5", 0f, 1f),
                Enum("stationary", "never", "withinView betweenViews always never"),
                Path("fontPath"),
                Float("fontSize", "0.045", 0.001f, 1.5f),
                Enum("horizontalAlignment", "left", "left center right"),
                Enum("verticalAlignment", "center", "top center bottom"),
                Color("color", null),
                Color("backgroundColor", null),
                Float("opacity", "1", 0f, 1f),
                Bool("visible", "true"),
                Float("zIndex", "45"),
            ]),
            new ThemeElementSpec("rating", ThemeElementGroup.Secondary, ThemeElementViews.SystemAndGamelist,
            [
                Pair("pos", null),
                Pair("size", "0 0.06", 0.01f, 1f) with { MaxY = 0.5f, Rule = PairRule.OneAxisOnly },
                Pair("origin", "0 0", 0f, 1f),
                Float("rotation", "0"),
                Pair("rotationOrigin", "0.5 0.5", 0f, 1f),
                Enum("stationary", "never", "withinView betweenViews always never"),
                Bool("hideIfZero", "false"),
                Str("gameselector", null),
                UInt("gameselectorEntry", "0", 0f, null) with { OnlyIn = ThemeViewScope.System },
                Enum("interpolation", null, "nearest linear") with { Computed = ComputedDefault.InterpolationByRotation },
                Color("color", "FFFFFFFF"),
                Path("filledPath"),
                Path("unfilledPath"),
                Bool("overlay", "true"),
                Float("opacity", "1", 0f, 1f),
                Bool("visible", "true"),
                Float("zIndex", "45"),
            ]),
            new ThemeElementSpec("gameselector", ThemeElementGroup.Special, ThemeElementViews.System,
            [
                Enum("selection", "random", "random lastplayed mostplayed"),
                UInt("gameCount", "1", 1f, 30f),
                Bool("allowDuplicates", "false"),
            ]),
            new ThemeElementSpec("helpsystem", ThemeElementGroup.Special, ThemeElementViews.SystemAndGamelist,
            [
                Pair("pos", null) with { Computed = ComputedDefault.HelpPosByOrientation },
                Pair("posDimmed", null) with { DefaultSameAs = "pos" },
                Pair("origin", "0 0", 0f, 1f),
                Pair("originDimmed", null, 0f, 1f) with { DefaultSameAs = "origin" },
                Float("rotation", "0"),
                Pair("rotationOrigin", "0.5 0.5", 0f, 1f),
                Color("textColor", "777777FF"),
                Color("textColorDimmed", null) with { DefaultSameAs = "textColor" },
                Color("iconColor", "777777FF"),
                Color("iconColorDimmed", null) with { DefaultSameAs = "iconColor" },
                Path("fontPath"),
                Float("fontSize", null, 0.001f, 1.5f) with { Computed = ComputedDefault.HelpFontSizeByOrientation },
                Float("fontSizeDimmed", null, 0.001f, 1.5f) with { DefaultSameAs = "fontSize" },
                Enum("scope", "shared", "shared view menu none"),
                List("entries", "all", "all back start a b x y l r lt rt left/right down up up/down up/down/left/right ltrt lr thumbstickclick", 0),
                Enum("entryLayout", "iconFirst", "iconFirst textFirst"),
                Float("entryRelativeScale", "1", 0.2f, 3f),
                Float("entrySpacing", "0.00833", 0f, 0.04f),
                Float("entrySpacingDimmed", null, 0f, 0.04f) with { DefaultSameAs = "entrySpacing" },
                Float("iconTextSpacing", "0.00416", 0f, 0.04f),
                Float("iconTextSpacingDimmed", null, 0f, 0.04f) with { DefaultSameAs = "iconTextSpacing" },
                Enum("letterCase", "uppercase", "uppercase lowercase capitalize"),
                Color("backgroundColor", "00000000"),
                Color("backgroundColorEnd", null) with { DefaultSameAs = "backgroundColor" },
                Enum("backgroundGradientType", "horizontal", "horizontal vertical"),
                Pair("backgroundHorizontalPadding", "0 0", 0f, 1f),
                Pair("backgroundVerticalPadding", "0 0", 0f, 1f),
                Float("backgroundCornerRadius", "0", 0f, 0.5f),
                Float("opacity", "1", 0.2f, 1f),
                Float("opacityDimmed", null, 0.2f, 1f) with { DefaultSameAs = "opacity" },
                Keyed("customButtonIcon", "button", "dpad_updown dpad_leftright dpad_all thumbstick_click button_l button_r button_lr button_lt button_rt button_ltrt button_a_XBOX button_b_XBOX button_x_XBOX button_y_XBOX button_back_XBOX button_start_XBOX button_back_XBOX360 button_start_XBOX360 button_a_PS button_b_PS button_x_PS button_y_PS button_back_PS123 button_start_PS123 button_back_PS4 button_start_PS4 button_back_PS5 button_start_PS5 button_a_switch button_b_switch button_x_switch button_y_switch button_back_switch button_start_switch button_a_SNES button_b_SNES button_x_SNES button_y_SNES button_back_SNES button_start_SNES"),
            ]),
            new ThemeElementSpec("systemstatus", ThemeElementGroup.Special, ThemeElementViews.SystemAndGamelist,
            [
                Pair("pos", "0.982 0.016"),
                Float("height", "0.035", 0.01f, 0.5f),
                Pair("origin", "1 0", 0f, 1f),
                Float("rotation", "0"),
                Pair("rotationOrigin", "0.5 0.5", 0f, 1f),
                Enum("scope", "shared", "shared view menu none"),
                Path("fontPath"),
                Float("textRelativeScale", "0.9", 0.5f, 1f),
                Color("color", "FFFFFFFF"),
                Color("backgroundColor", "00000000"),
                Color("backgroundColorEnd", null) with { DefaultSameAs = "backgroundColor" },
                Enum("backgroundGradientType", "horizontal", "horizontal vertical"),
                Pair("backgroundHorizontalPadding", "0 0", 0f, 1f),
                Pair("backgroundVerticalPadding", "0 0", 0f, 1f),
                Float("backgroundCornerRadius", "0", 0f, 0.5f),
                List("entries", "all", "bluetooth wifi cellular battery all", 0),
                Float("entrySpacing", "0.005", 0f, 0.04f),
                Keyed("customIcon", "icon", "icon_bluetooth icon_wifi icon_cellular icon_battery_charging icon_battery_low icon_battery_medium icon_battery_high icon_battery_full"),
                Float("opacity", "1", 0f, 1f),
            ]),
            new ThemeElementSpec("clock", ThemeElementGroup.Special, ThemeElementViews.SystemAndGamelist,
            [
                Pair("pos", "0.018 0.016"),
                Pair("size", null),
                Pair("origin", "0 0", 0f, 1f),
                Float("rotation", "0"),
                Pair("rotationOrigin", "0.5 0.5", 0f, 1f),
                Enum("scope", "shared", "shared view menu none"),
                Path("fontPath"),
                Float("fontSize", "0.035", 0.001f, 1.5f),
                Enum("horizontalAlignment", "left", "left center right"),
                Enum("verticalAlignment", "center", "top center bottom"),
                Color("color", "FFFFFFFF"),
                Color("backgroundColor", "00000000"),
                Color("backgroundColorEnd", null) with { DefaultSameAs = "backgroundColor" },
                Enum("backgroundGradientType", "horizontal", "horizontal vertical"),
                Pair("backgroundHorizontalPadding", "0 0", 0f, 1f),
                Pair("backgroundVerticalPadding", "0 0", 0f, 1f),
                Float("backgroundCornerRadius", "0", 0f, 0.5f),
                Str("format", "%H:%M"),
                Float("opacity", "1", 0f, 1f),
            ]),
            new ThemeElementSpec("sound", ThemeElementGroup.Special, ThemeElementViews.All,
            [
                Path("path"),
            ]),
        ];

        private static readonly Dictionary<string, ThemeElementSpec> ByType = Elements.ToDictionary(e => e.Type, StringComparer.Ordinal);

        public static ThemeElementSpec? Find(string type) => ByType.GetValueOrDefault(type);

        public static int PropertyCount => Elements.Sum(e => e.Properties.Count);

        private static ThemePropertySpec Pair(string name, string? def, float? min = null, float? max = null) =>
            new(name, ThemePropertyType.NormalizedPair) { Default = def, Min = min, Max = max };

        private static ThemePropertySpec Path(string name) => new(name, ThemePropertyType.Path);

        private static ThemePropertySpec Bool(string name, string? def) => new(name, ThemePropertyType.Boolean) { Default = def };

        private static ThemePropertySpec Color(string name, string? def) => new(name, ThemePropertyType.Color) { Default = def };

        private static ThemePropertySpec UInt(string name, string? def, float? min = null, float? max = null) =>
            new(name, ThemePropertyType.UnsignedInteger) { Default = def, Min = min, Max = max };

        private static ThemePropertySpec Float(string name, string? def, float? min = null, float? max = null) =>
            new(name, ThemePropertyType.Float) { Default = def, Min = min, Max = max };

        private static ThemePropertySpec Str(string name, string? def) => new(name, ThemePropertyType.String) { Default = def };

        private static ThemePropertySpec Enum(string name, string? def, string values) =>
            new(name, ThemePropertyType.String) { Default = def, Shape = ThemeValueShape.Enum, Values = ThemeLists.Split(values) };

        private static ThemePropertySpec List(string name, string? def, string values, int maxItems) =>
            new(name, ThemePropertyType.String) { Default = def, Shape = ThemeValueShape.List, Values = ThemeLists.Split(values), MaxItems = maxItems };

        private static ThemePropertySpec Keyed(string name, string attribute, string keys) =>
            new(name, ThemePropertyType.Path) { Shape = ThemeValueShape.Keyed, KeyAttribute = attribute, Values = ThemeLists.Split(keys) };
    }
}
